# Generated by Django 4.2.13 on 2024-06-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("borrow_price", models.IntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FIC", "Fiction"),
                            ("NF", "Non-Fiction"),
                            ("MYST", "Mystery"),
                            ("SCI-FI", "Science Fiction"),
                            ("FANT", "Fantasy"),
                            ("BIO", "Biography"),
                            ("HIST", "History"),
                            ("ROM", "Romance"),
                            ("THR", "Thriller"),
                            ("PHI", "Philosophy"),
                            ("POE", "Poetry"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
