# Generated by Django 4.2.13 on 2024-06-18 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_reviewmodel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewmodel",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="book.bookmodel"
            ),
        ),
    ]
